### ISSUE TITLE
Using TsconfigPathsPlugin

### ISSUE THREAD

**Issue by IvanovRoman** [DiFuks/typedoc-theme-hierarchy#1]
Why are you using `TsconfigPathsPlugin` if you don't have an `path` in `tsconfig.json`?
https://github.com/DiFuks/typedoc-theme-hierarchy/blob/7ea54667c115904b2e937f8b1b7c347e2fc9b08c/webpack.config.ts#L40

**Comment by DiFuks** [comment]
I've used "paths" in "tsconfig" in the past. The plugin remained as an artifact. Deleted in the last commit. Thanks!
