### ISSUE TITLE
Update dependency for new version of typedoc

### ISSUE THREAD

**Issue by donald-richardson-dxd** [DiFuks/typedoc-theme-hierarchy#10]
Support typedoc 0.23.2

**Comment by DiFuks** [comment]
What is the problem? I just updated the typedoc to the latest version [in my pet project](https://docs.new.fuks.ru/) and everything is working fine

**Comment by donald-richardson-dxd** [comment]
I get a “Can’t resolve dependency” error using npm.

Your typedoc dependency is:

"typedoc": "^0.22.9"

The latest typedoc is 0.23.2. For semantic versions that begin with 0 the caret works like ~ in that it will only allow patch updates and not minor updates.

From: Dmitriy Fuks ***@***.***>
Date: Wednesday, June 29, 2022 at 2:41 PM
To: DiFuks/typedoc-theme-hierarchy ***@***.***>
Cc: Donald Richardson ***@***.***>, Author ***@***.***>
Subject: Re: [DiFuks/typedoc-theme-hierarchy] Update dependency for new version of typedoc (Issue #10)

What is the problem? I just updated the typedoc to the latest version in my pet project<https://us01.z.antigena.com/l/g74E8VCS55m-lfzJrvtlFsz~SrJRGaz9ot2_bGHX6SkA2AIT4XxqMUDXS2r_v~00xYv2xt0FEVps_uth1SPuecOoFJFE9VR7ssOhCB1XL-KBQ35APb6bAE38bmkIWWgCZ4WSVVPA9zpmvSwBP8w5wBdHSSb> and everything is working fine

**Comment by DiFuks** [comment]
> The latest typedoc is 0.23.2. For semantic versions that begin with 0 the caret works like ~ in that it will only allow patch updates and not minor updates.

Thank you! I did not know. Fixed. Please update to 1.3.0
