### ISSUE TITLE
Assets aren't copied over if `out` isn't explicitly defined.

### ISSUE THREAD

**Issue by avoliva** [DiFuks/typedoc-theme-hierarchy#17]
If you don't have `out` explicitly defined in your config or in the typedoc CLI, the custom assets are not copied over.

Looks like it may come from typedoc's end since `getValue('out')` is not returning the default value.
https://github.com/DiFuks/typedoc-theme-hierarchy/blob/1d1ca8b3212c11b6829bbe2cdd27f674d4be5b19/src/themes/OverrideTheme.tsx#L16

**Comment by DiFuks** [comment]
Fixed 3.0.3

https://github.com/DiFuks/typedoc-theme-hierarchy/blob/master/src/themes/OverrideTheme.tsx#L18

It looks like a workaround. So I left an issue in the typedoc repository

https://github.com/TypeStrong/typedoc/issues/2195
