### ISSUE TITLE
how to support `customCss` option ? 

### ISSUE THREAD

**Issue by gitawego** [DiFuks/typedoc-theme-hierarchy#20]
first, thanks for your great theme

But it seems [customCss](https://typedoc.org/options/output/#customcss) is not supported by this theme, when I add this option, the css is not taken into account. I'd like to know how can I customize a little bit this theme ?

thanks in advance!

**Comment by DiFuks** [comment]
fixed 4.1.0

**Comment by DiFuks** [comment]
The name of my css file matched what the typedoc generates for custom css and overwrote it 🙈
