### ISSUE TITLE
Local paths included in hierarchy.

### ISSUE THREAD

**Issue by Owen3H** [DiFuks/typedoc-theme-hierarchy#21]
Currently the hierarchy root is resolved to a path on my local machine.

Instead, it should default to the project root. 
However, if "basePath" is specified within `typedoc.json` it should use that as the root.

![image](https://github.com/DiFuks/typedoc-theme-hierarchy/assets/48495634/252c8cb3-4b6d-47e4-bfa1-83742adce959)

**Comment by DiFuks** [comment]
fixed v4.0.1

**Comment by orangebokov** [comment]
Thanks, great theme! But, unfortunately, the same problem... Mac os m1, v4.1.2

<img width="281" alt="Снимок экрана 2023-10-30 в 22 38 36" src="https://github.com/DiFuks/typedoc-theme-hierarchy/assets/39646729/e5e52668-1c94-4343-aacd-3a262700f483">

I solved this problem for myself as follows:

navigation.js

    const navigation = (context) => (props) => {
    let categories = formatFileHierarchy(props.model.project.children || []);
    
    do {
        var key = Object.keys(categories.categories)[0]
        categories = categories.categories[key]
    }
    while (key != "front")

thereby removing the unnecessary branch above "front"

<img width="245" alt="Снимок экрана 2023-10-30 в 22 48 59" src="https://github.com/DiFuks/typedoc-theme-hierarchy/assets/39646729/2c974e1c-b243-4f1b-9d7d-6278725f8d20">

**Comment by orangebokov** [comment]
Just checked

Apparently this is because entryPoints is set in relative in my configuration

    "entryPoints": ["../../front/"],

**Comment by orangebokov** [comment]
in fact, even if I do

    {
      "entryPoints": ["src"],
      "entryPointStrategy": "Expand",
      "out": "public/docs",
      "plugin": ["typedoc-theme-hierarchy"],
      "theme": "hierarchy",
      "tsconfig": "./tsconfig.json",
      "name": "Project name"
    }

it will still capture the "src" folder

<img width="259" alt="Снимок экрана 2023-10-30 в 23 45 29" src="https://github.com/DiFuks/typedoc-theme-hierarchy/assets/39646729/5d124c70-7b1d-4fbe-a299-47d3ab471607">
