### ISSUE TITLE
Could you update README with the minimum version of Nodejs?

### ISSUE THREAD

**Issue by pomeloEater** [DiFuks/typedoc-theme-hierarchy#25]
```
[error] The plugin typedoc-theme-hierarchy could not be loaded.
[error] D:\Development2023\gtmap2\gtmap2-for-uis-dev\gtmap2-for-uis-front-end\node_modules\typedoc-theme-hierarchy\dist\themes\OverrideTheme.js:26
        this._contextCache ||= new OverrideThemeContext_1.OverrideThemeContext(this, page, this.application.options);
                           ^^^

SyntaxError: Unexpected token '||='
```
- Error happened: `npx typedoc`
- Node.js Version: 14.16.0
- typescript: 5.1.6
- typedoc: 0.24.8
- typedoc-theme-hierarchy: 4.1.0

And I found it that Logical Or assignment(||=) need Node.js version 15.0.0. (mdn web docs link [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_OR_assignment#browser_compatibility))
Could you put this in the README documentation?

**Comment by DiFuks** [comment]
done!
