### ISSUE TITLE
Preserve the 'on this page' section from the default theme

### ISSUE THREAD

**Issue by krnl0138** [DiFuks/typedoc-theme-hierarchy#27]
Is there a way to have the default right side bar section called 'on this page' in Hierarchy theme?
I think it's helpful to glance on the structure of the module from this section, and you can navigate to its parts, instead of scrolling back to the top to refresh in mind what does this module have

Steps to reproduce: 
- set theme to 'default' in `typedoc.json`
- access any module

**Comment by DiFuks** [comment]
@krnl0138 It seems this has been fixed. Please check!
