### ISSUE TITLE
The first character is missing from highest levels of the hierarchy

### ISSUE THREAD

**Issue by brannonvann** [DiFuks/typedoc-theme-hierarchy#29]
Nice plugin! I installed and configured without much trouble but noticed that the first characters are missing from the highest level only. Here is an image (should be "constants" and "utils"). I checked versions 4.0.0-4.1.2 and they all had this problem. I'm using `typedoc@0.25.4`. In case it plays a part I'm using `"entryPointStrategy": "packages"` however, I'm just pointing to this single package at the moment. My single package typedoc config just points to the entry file, no other config.

<img width="384" alt="image" src="https://github.com/DiFuks/typedoc-theme-hierarchy/assets/40714964/a35d1a87-3073-4017-a603-80efca580e15">

**Comment by DiFuks** [comment]
Unfortunately, I developed and tested the plugin only for `entryPointStrategy: Expand`. I might be able to implement support for another strategy, but I'm afraid it would require significant modifications and take up a lot of time, which I currently have very little of :(
