### ISSUE TITLE
The Dark

### ISSUE THREAD

**Issue by huineng** [DiFuks/typedoc-theme-hierarchy#5]
Hi your dark them is having an element in white

![image](https://user-images.githubusercontent.com/3482445/152570427-276100dd-e6d6-497a-b444-f3cb2f80ce41.png)

![image](https://user-images.githubusercontent.com/3482445/152570303-b780d0b9-e19e-4cc2-b9f0-1dec95577e55.png)

thanks

**Comment by DiFuks** [comment]
@huineng fixed
