### ISSUE TITLE
Include non-exported functions in the generated docs?

### ISSUE THREAD

**Issue by phuongduyphan** [DiFuks/typedoc-theme-hierarchy#9]
Currently, only functions declared with export are in the docs, is there any way to include non-exported functions in the docs as well?

**Comment by dcallus** [comment]
there is a plugin for non-exported docs. https://www.npmjs.com/package/typedoc-plugin-not-exported

There me be others, have a look and see which best suits your needs

**Comment by DiFuks** [comment]
typedoc does not add  that are not exported. This can be solved with plugins, as @dcallus correctly noted. I am closing this issue.
